name: flutter_demo_dws
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3 # Thêm để lưu trữ cục bộ

  # Firebase & Authentication
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1

  # Utility packages
  wakelock_plus: ^1.2.0
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
